defaults:
  - preprocessor@msm_ner.preprocessor: bert_retokenization
  - metrics@msm_ner.metrics.train_metrics:
      - accuracy
  - metrics@msm_ner.metrics.val_metrics:
      - accuracy
  - metrics@msm_ner.metrics.test_metrics:
      - accuracy


msm_ner:
  _target_: datamodule.dataset.ClassificationJSONDataset

  name: msm_ner

  raw_file: data/msm/ner/msmarco_ner_60000_10_2022_01_14-16-41-48.json

  train_file: data/msm/ner/train.jsonl
  val_file: data/msm/ner/validation.jsonl
  test_file: data/msm/ner/test.jsonl

  label_file: data/msm/ner/labels.pkl

  num_train_samples: 40000
  num_test_samples: 20000

  num_classes: 18

  to_probabilities:
    _target_: torch.nn.Identity

  loss:
    _target_: torch.nn.CrossEntropyLoss