defaults:
  - metrics@msm_bm25.metrics.train_metrics:
      - mse
  - metrics@msm_bm25.metrics.val_metrics:
      - mse
  - metrics@msm_bm25.metrics.test_metrics:
      - mse

msm_bm25:
  _target_: datamodule.dataset.JSONDataset

  name: msm_bm25

  raw_file: data/msm/bm25/msmarco_bm25_dataset.json

  train_file: data/msm/bm25/train.jsonl
  val_file: data/msm/bm25/validation.jsonl
  test_file: data/msm/bm25/test.jsonl

  num_train_samples: 9000
  num_test_samples: 1000

  normalize_targets: true

  to_probabilities:
    _target_: torch.nn.Identity