defaults:
  - preprocessor@msm_ner.preprocessor: bert_retokenization
  - metrics@msm_ner.metrics.train_metrics:
      - accuracy
      - f1score
  - metrics@msm_ner.metrics.val_metrics:
      - accuracy
      - f1score
  - metrics@msm_ner.metrics.test_metrics:
      - accuracy
      - f1score


msm_ner:
  _target_: datamodule.dataset.ClassificationJSONDataset

  name: msm_ner

  raw_file: data/msm/ner/msmarco_ner_100000_10_2022_04_28-18-29-40.json

  train_file: data/msm/ner/train.json
  val_file: data/msm/ner/validation.json
  test_file: data/msm/ner/test.json

  label_file: data/msm/ner/labels.pkl

  num_train_samples: 950000
  num_test_samples: 50000

  num_classes: 18

  to_probabilities:
    _target_: torch.nn.Softmax

  loss:
    _target_: torch.nn.CrossEntropyLoss


  metrics:
    train_metrics:
      f1score:
        num_classes: 18
    val_metrics:
      f1score:
        num_classes: 18
    test_metrics:
      f1score:
        num_classes: 18