defaults:
  - preprocessor@msm_bm25.preprocessor: bert
  - metrics@msm_bm25.metrics.train_metrics:
      - accuracy
      - f1score
  - metrics@msm_bm25.metrics.val_metrics:
      - accuracy
      - f1score
  - metrics@msm_bm25.metrics.test_metrics:
      - accuracy
      - f1score

msm_bm25:
  _target_: datamodule.dataset.RegressionJSONDataset

  name: msm_bm25

  raw_file: data/msm/bm25/msmarco_bm25_60000_10_2022_04_08-15-40-06.json

  train_file: data/msm/bm25/train.jsonl
  val_file: data/msm/bm25/validation.jsonl
  test_file: data/msm/bm25/test.jsonl

  num_train_samples: 40000
  num_test_samples: 20000

  # 1 means no buckets at all i.e. regression
  num_buckets: 10

  to_probabilities:
    _target_: torch.nn.Softmax
    dim: -1

  loss:
    _target_: torch.nn.CrossEntropyLoss

  # ---------- overrides ----------
  metrics:
    train_metrics:
      f1score:
        num_classes: ${datamodule.dataset.datasets.msm_bm25.num_buckets}
    val_metrics:
      f1score:
        num_classes: ${datamodule.dataset.datasets.msm_bm25.num_buckets}
    test_metrics:
      f1score:
        num_classes: ${datamodule.dataset.datasets.msm_bm25.num_buckets}