trec2019:
  _target_: datamodule.dataset.TREC2019

  name: trec2019

  data_file: data/trec/trecdl_passage_2019/data.h5
  train_file: data/trec/trecdl_passage_2019/fold_0/train_pointwise.h5
  val_file: data/trec/trecdl_passage_2019/fold_0/val.h5
  test_file: data/trec/trecdl_passage_2019/fold_0/test.h5

  qrels_file: data/trec/trec_eval_files/2019qrels-pass.txt

