defaults:
  - model: multitask_model
  - datamodule: multitask
  - loop: multitask_loop

gpus: 1
num_workers: 8
random_seed: 1590258941

training:
  epochs: 100
  validate_every_n_steps: null
  warmup_steps: 10000
  batch_size: 32
  accumulate_batches: 1
  precision: 16
  # checkpointing
  save_ckpts: 3
  monitor: val/trec_map/trec2019
  mode: max
  patience: 3

testing:
  batch_size: ${training.batch_size}
  precision: 16
  ckpt_path: null
  run_id: null

logger:
  project: mtl-ranking
  _target_: logger.loggers.WandbMinMaxLogger
log_gradients: False

hydra:
  run:
    dir: outputs/single/${model.body._target_}/${loop.loss._target_}/${now:%Y-%m-%d}/${now:%H-%M-%S}

  sweep:
    dir: outputs/sweep/${model.body._target_}/${loop.loss._target_}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    # subdir: lr:${loop.optimizer.lr}