defaults:
  - body: bert_base_uncased
  # - heads@heads.msm_ner: msm_ner
  - heads@heads.msm_bm25: msm_bm25
  - heads@heads.trec2019_pairwise: trec2019_pairwise


_target_: model.multitask.MultiTaskModel
