defaults:
  - pooler: span_average

_target_: model.head.mlp.MLP
h_dim: 128
out_dim: ${datamodule.dataset.datasets.msm_coref.num_classes}
dropout: 0.2
sigmoid_out: false

pooler:
  layers: [ 5 ]
  # 2 * pooler.in_dim
  out_dim: 1536