defaults:
  - dataset: mtl
  - sampler@train_sampler_cfg: round_robin
  - sampler@val_sampler_cfg: sequential
  - sampler@test_sampler_cfg: sequential

_target_: datamodule.multitask_datamodule.MTLDataModule

train_batch_size: ${training.batch_size}
test_batch_size: ${testing.batch_size}

num_workers: ${num_workers}
pin_memory: True