defaults:
  - dataset: mtl
  - sampler@train_sampler: random_proportional
  - sampler@val_sampler: sequential
  - sampler@test_sampler: sequential

_target_: datamodule.multitask_datamodule.MTLDataModule

train_batch_size: ${training.batch_size}
test_batch_size: ${testing.batch_size}

num_workers: ${num_workers}
pin_memory: True